# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\sign_in.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import logging

from PyQt5 import QtCore, QtGui, QtWidgets
import MainWindow

class Ui_Dialog_SignIn(object):

    dialog_hnd = None
    def openWindow(self):
        logging.debug("Opening MainWindow")

        self.window = QtWidgets.QMainWindow()
        self.ui = MainWindow.Ui_MainWindow()

        self.ui.login = self.lineEdit_login.text()
        self.ui.password = self.lineEdit_pass.text()

        self.ui.setupUi(self.window)
        self.dialog_hnd.close()
        self.window.show()

    def setupUi(self, Dialog_SignIn):
        self.dialog_hnd = Dialog_SignIn
        Dialog_SignIn.setObjectName("Dialog_SignIn")
        Dialog_SignIn.resize(220, 136)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_SignIn.sizePolicy().hasHeightForWidth())
        Dialog_SignIn.setSizePolicy(sizePolicy)
        Dialog_SignIn.setFixedSize(Dialog_SignIn.size())
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_SignIn)
        self.buttonBox.setGeometry(QtCore.QRect(20, 100, 191, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog_SignIn)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 211, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_login = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_login.setObjectName("label_login")
        self.horizontalLayout.addWidget(self.label_login)
        spacerItem = QtWidgets.QSpacerItem(33, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEdit_login = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_login.setEnabled(True)
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.horizontalLayout.addWidget(self.lineEdit_login)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_password = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_password.setObjectName("label_password")
        self.horizontalLayout_2.addWidget(self.label_password)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lineEdit_pass = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pass.sizePolicy().hasHeightForWidth())
        self.lineEdit_pass.setSizePolicy(sizePolicy)
        self.lineEdit_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_pass.setObjectName("lineEdit_pass")
        self.horizontalLayout_2.addWidget(self.lineEdit_pass)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog_SignIn)
        #self.buttonBox.accepted.connect(Dialog_SignIn.accept)
        self.buttonBox.accepted.connect(self.openWindow)
        self.buttonBox.rejected.connect(Dialog_SignIn.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_SignIn)

        self.lineEdit_login.setFocus()

    def retranslateUi(self, Dialog_SignIn):
        _translate = QtCore.QCoreApplication.translate
        Dialog_SignIn.setWindowTitle(_translate("Dialog_SignIn", "DA ChatManager"))
        self.label_login.setText(_translate("Dialog_SignIn", " Login:"))
        self.label_password.setText(_translate("Dialog_SignIn", " Password:"))
